org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)
forge_version=47.2.32
forge_version_range=[46,)
loader_version_range=[46,)
mapping_channel=official
mapping_version=1.20.1

mod_id=luckytntlib
mod_name=Lucky TNT Lib
mod_license=All Rights Reserved
mod_version=47.2.32.1
mod_group_id=libs.luckytntlib
mod_authors=SlimingHD, Fleshcrafter
mod_description=This mod acts as a library for TNT mods usually associated with the word "Lucky". It allows for quick creation and easy maintenance of TNT mods and is a hard dependency.