modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="luckytntlib"
version="1.19.2-1.0"
displayName="Lucky TNT Lib"
logoFile="logo.png"
credits="Created, updated and maintained by SlimingHD"
authors="SlimingHD"
description='''
This mod acts as a library for TNT mods usually associated with the word "Lucky".
It allows for quick creation and easy maintenance of TNT mods.
'''
[[dependencies.luckytntlib]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
