modLoader="javafml"
loaderVersion="[49,)"
license="All rights reserved"
[[mods]]
modId="luckytntlib"
version="49.0.2.0"
displayName="Lucky TNT Lib"
logoFile="logo.png"
credits="Created, updated and maintained by SlimingHD"
authors="SlimingHD, Fleshcrafter"
description='''
This mod acts as a library for TNT mods usually associated with the word "Lucky".
It allows for quick creation and easy maintenance of TNT mods and is a hard dependency.
'''
[[dependencies.luckytntlib]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3,1.21)"
    ordering="NONE"
    side="BOTH"
