modLoader="javafml"
loaderVersion="[48,)"
license="All rights reserved"
[[mods]]
modId="luckytntlib"
version="48.0.19.2"
displayName="Lucky TNT Lib"
logoFile="logo.png"
credits="Created, updated and maintained by SlimingHD"
authors="SlimingHD, Fleshcrafter"
description='''
This mod acts as a library for TNT mods usually associated with the word "Lucky".
It allows for quick creation and easy maintenance of TNT mods and is a hard dependency.
'''
[[dependencies.luckytntlib]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.20.3)"
    ordering="NONE"
    side="BOTH"
